<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books [
	<!ELEMENT books (book+)>
	<!ELEMENT book (name, author, price)>
	<!ATTLIST book id CDATA #REQUIRED>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT author (#PCDATA)>
	<!ELEMENT price (#PCDATA)>
]>
<books>
<!-- xml文件名应于根元素名一致 -->	
	<book id = "b01">
		<name>红楼梦</name>
		<author>曹雪芹</author>
		<price>99</price>
	</book>
	<book id = "b02">
		<name>三国演义</name>
		<author>罗贯中</author>
		<price>99</price>
	</book>
</books>